### ISSUE TITLE
String regex?

### ISSUE THREAD

**Issue by brandoncamenisch** [JDGrimes/wp-l10n-validator#40]
Hey @JDGrimes I was taking a look into using this tool and was wondering if there was regex support for ignoring strings/files as part of the configuration already? It seems this tool does most of what I want but can't seem to find anything in relation to that.

If there's not support could that be easily done through the bootstrap file and if so would you happen to have an example?

**Comment by JDGrimes** [comment]
No, there isn't a way to ignore strings/files via regex, but that is a great idea. I am super busy right now, but you could hack in some regexes around [this line](https://github.com/JDGrimes/wp-l10n-validator/blob/develop/wp-l10n-validator.php#L1802) to ignore strings. Ignoring files would go [in here](https://github.com/JDGrimes/wp-l10n-validator/blob/develop/wp-l10n-validator.php#L729). 

If you get it working, a PR adding this feature would definitely be welcome.

**Comment by brandoncamenisch** [comment]
Thanks @JDGrimes I think that info set me in the right direction. I'll submit a PR when I get around to working on this some more. Looking to use this in a CI setup where we're being fairly strict about localization and your tool was the best thing we could find to do the job. :smile:
